### PR TITLE
Use curly quotes in prose instead of apostrophes

### PR DESCRIPTION
**Pull request by zuzak**

### CODE REVIEW

**Comment by daniel-ac-martin** [comment]
Is there any benefit to this?

**Comment by zuzak** [comment]
It makes it consistent with the rest of the templates, mostly; otherwise it's a mix of curly and straight. Plus, it makes content designers happier.

**Comment by daniel-ac-martin** [comment]
Sounds like opinion is divided!

We should be consistent though. Can you point me to where the curly ones are?

**Comment by zuzak** [comment]
Here's one, for example: https://github.com/UKHomeOffice/docker-nginx-proxy-govuk/blob/master/html/partials/501.shtml

**Comment by daniel-ac-martin** [comment]
Thanks.

**Pull request merged**
