### PR TITLE
Update nginx proxy version to v4.2.0

### PR DESCRIPTION
**Pull request by chriswilliams13**
This add http2 functionality to the image

### CODE REVIEW

**Comment by chriswilliams13** [comment]
@daniel-ac-martin could you please review?

**Review by daniel-ac-martin — APPROVED** [review]
LGTM.

**Comment by chriswilliams13** [comment]
@daniel-ac-martin should this have tagged a new release? or is a manual process in place?

**Comment by daniel-ac-martin** [comment]
@chriswilliams13: Yes, sorry there is a manual process. (Needs a new tag.) I've triggered it now.

**Pull request merged**
